name: Construct Import Library

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
# https://github.com/marketplace/actions/github-push
jobs:
  construct-import-lib:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'github-actions[bot]' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v5
      - run: python make_release.py
      - run: |
          echo ${{ github.event.pull_request.head.user.name }}
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Make header only import library"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.head_ref }}