name: Run Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y ninja-build
      - run: cmake -S . -B ObjParserTests -G Ninja
      - run: cmake --build ObjParserTests
      - run: ctest --test-dir ObjParserTests --output-on-failure
  
  build_windows:
    runs-on: windows-latest
    if: github.actor == 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S . -B ObjParserTests -G "Visual Studio 17 2022" -A x64
      - run: cmake --build ObjParserTests
      - run: ctest --test-dir ObjParserTests --output-on-failure

  build_mac:
    runs-on: macos-latest
    if: github.actor == 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S . -B ObjParserTests -G Ninja
      - run: cmake --build ObjParserTests
      - run: ctest --test-dir ObjParserTests --output-on-failure