name: Run Tests

on:
  pull_request:
  workflow_call:

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: generate header only
        run: python make_release.py 0
      - name: Build and Test
        run: |
          sudo apt update && sudo apt install -y ninja-build
          cmake -S . -B ObjParserTests -G Ninja
          cmake --build ObjParserTests
          ctest --test-dir ObjParserTests --output-on-failure

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: generate header only
        run: python make_release.py 0
      - name: Build and Test
        run: |
          cmake -S . -B ObjParserTests -G "Visual Studio 17 2022" -A x64
          cmake --build ObjParserTests
          ctest --test-dir ObjParserTests --output-on-failure

  build_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: generate header only
        run: python make_release.py 0
      - name: Build and Test
        run: |
          cmake -S . -B ObjParserTests -G Ninja
          cmake --build ObjParserTests
          ctest --test-dir ObjParserTests --output-on-failure